In [1]:
import pandas as pd
import os

os.chdir('..')

df_alisa = pd.read_csv('output/3.csv')
df_alisa.head()

,frame_idx,nose_x,nose_y,nose_z,left_eye_x,left_eye_y,left_eye_z,right_eye_x,right_eye_y,right_eye_z,...,right_pinky_finger1_z,right_pinky_finger2_x,right_pinky_finger2_y,right_pinky_finger2_z,right_pinky_finger3_x,right_pinky_finger3_y,right_pinky_finger3_z,right_pinky_finger4_x,right_pinky_finger4_y,right_pinky_finger4_z
0,0,0.464281,-1.298155,5.528,0.516928,-1.403135,5.811,0.424170,-1.333023,5.483,...,5.312,0.520621,-0.662786,5.354,0.393736,-0.700351,5.439,0.363807,-0.694814,5.396
1,1,0.456806,-1.286269,5.439,0.516928,-1.403135,5.811,0.417440,-1.311871,5.396,...,5.271,0.530466,-0.642484,5.190,0.384542,-0.683998,5.312,0.372843,-0.661247,5.271
2,2,0.460502,-1.287588,5.483,0.512569,-1.391304,5.762,0.420766,-1.322325,5.439,...,5.312,0.534136,-0.657587,5.312,0.390623,-0.694814,5.396,0.378714,-0.671659,5.354
3,3,0.456806,-1.277255,5.439,0.512569,-1.391304,5.762,0.417440,-1.311871,5.396,...,5.271,0.560611,-0.637656,5.151,0.442696,-0.678718,5.271,0.390306,-0.661247,5.271
4,4,0.460502,-1.287588,5.483,0.516928,-1.403135,5.811,0.417440,-1.311871,5.396,...,5.230,0.472539,-0.657587,5.312,0.349918,-0.668288,5.190,0.326624,-0.673439,5.230

In [2]:
print(df_alisa.head().to_markdown())

|    |   frame_idx |   nose_x |   nose_y |   nose_z |   left_eye_x |   left_eye_y |   left_eye_z |   right_eye_x |   right_eye_y |   right_eye_z |   left_ear_x |   left_ear_y |   left_ear_z |   right_ear_x |   right_ear_y |   right_ear_z |   left_shoulder_x |   left_shoulder_y |   left_shoulder_z |   right_shoulder_x |   right_shoulder_y |   right_shoulder_z |   left_elbow_x |   left_elbow_y |   left_elbow_z |   right_elbow_x |   right_elbow_y |   right_elbow_z |   left_wrist_x |   left_wrist_y |   left_wrist_z |   right_wrist_x |   right_wrist_y |   right_wrist_z |   left_hip_x |   left_hip_y |   left_hip_z |   right_hip_x |   right_hip_y |   right_hip_z |   left_knee_x |   left_knee_y |   left_knee_z |   right_knee_x |   right_knee_y |   right_knee_z |   left_ankle_x |   left_ankle_y |   left_ankle_z |   right_ankle_x |   right_ankle_y |   right_ankle_z |   left_big_toe_x |   left_big_toe_y |   left_big_toe_z |   left_small_toe_x |   left_small_toe_y |   left_small_toe_z |   left_heel_x |   left_heel_y |   left_heel_z |   right_big_toe_x |   right_big_toe_y |   right_big_toe_z |   right_small_toe_x |   right_small_toe_y |   right_small_toe_z |   right_heel_x |   right_heel_y |   right_heel_z |   face-0_x |   face-0_y |   face-0_z |   face-1_x |   face-1_y |   face-1_z |   face-2_x |   face-2_y |   face-2_z |   face-3_x |   face-3_y |   face-3_z |   face-4_x |   face-4_y |   face-4_z |   face-5_x |   face-5_y |   face-5_z |   face-6_x |   face-6_y |   face-6_z |   face-7_x |   face-7_y |   face-7_z |   face-8_x |   face-8_y |   face-8_z |   face-9_x |   face-9_y |   face-9_z |   face-10_x |   face-10_y |   face-10_z |   face-11_x |   face-11_y |   face-11_z |   face-12_x |   face-12_y |   face-12_z |   face-13_x |   face-13_y |   face-13_z |   face-14_x |   face-14_y |   face-14_z |   face-15_x |   face-15_y |   face-15_z |   face-16_x |   face-16_y |   face-16_z |   face-17_x |   face-17_y |   face-17_z |   face-18_x |   face-18_y |   face-18_z |   face-19_x |   face-19_y |   face-19_z |   face-20_x |   face-20_y |   face-20_z |   face-21_x |   face-21_y |   face-21_z |   face-22_x |   face-22_y |   face-22_z |   face-23_x |   face-23_y |   face-23_z |   face-24_x |   face-24_y |   face-24_z |   face-25_x |   face-25_y |   face-25_z |   face-26_x |   face-26_y |   face-26_z |   face-27_x |   face-27_y |   face-27_z |   face-28_x |   face-28_y |   face-28_z |   face-29_x |   face-29_y |   face-29_z |   face-30_x |   face-30_y |   face-30_z |   face-31_x |   face-31_y |   face-31_z |   face-32_x |   face-32_y |   face-32_z |   face-33_x |   face-33_y |   face-33_z |   face-34_x |   face-34_y |   face-34_z |   face-35_x |   face-35_y |   face-35_z |   face-36_x |   face-36_y |   face-36_z |   face-37_x |   face-37_y |   face-37_z |   face-38_x |   face-38_y |   face-38_z |   face-39_x |   face-39_y |   face-39_z |   face-40_x |   face-40_y |   face-40_z |   face-41_x |   face-41_y |   face-41_z |   face-42_x |   face-42_y |   face-42_z |   face-43_x |   face-43_y |   face-43_z |   face-44_x |   face-44_y |   face-44_z |   face-45_x |   face-45_y |   face-45_z |   face-46_x |   face-46_y |   face-46_z |   face-47_x |   face-47_y |   face-47_z |   face-48_x |   face-48_y |   face-48_z |   face-49_x |   face-49_y |   face-49_z |   face-50_x |   face-50_y |   face-50_z |   face-51_x |   face-51_y |   face-51_z |   face-52_x |   face-52_y |   face-52_z |   face-53_x |   face-53_y |   face-53_z |   face-54_x |   face-54_y |   face-54_z |   face-55_x |   face-55_y |   face-55_z |   face-56_x |   face-56_y |   face-56_z |   face-57_x |   face-57_y |   face-57_z |   face-58_x |   face-58_y |   face-58_z |   face-59_x |   face-59_y |   face-59_z |   face-60_x |   face-60_y |   face-60_z |   face-61_x |   face-61_y |   face-61_z |   face-62_x |   face-62_y |   face-62_z |   face-63_x |   face-63_y |   face-63_z |   face-64_x |   face-64_y |   face-64_z |   face-65_x |   face-65_y |   face-65_z |   face-66_x |   face-66_y |   face-66_z |   face-67_x |   face-67_y |   face-67_z |   left_hand_root_x |   left_hand_root_y |   left_hand_root_z |   left_thumb1_x |   left_thumb1_y |   left_thumb1_z |   left_thumb2_x |   left_thumb2_y |   left_thumb2_z |   left_thumb3_x |   left_thumb3_y |   left_thumb3_z |   left_thumb4_x |   left_thumb4_y |   left_thumb4_z |   left_forefinger1_x |   left_forefinger1_y |   left_forefinger1_z |   left_forefinger2_x |   left_forefinger2_y |   left_forefinger2_z |   left_forefinger3_x |   left_forefinger3_y |   left_forefinger3_z |   left_forefinger4_x |   left_forefinger4_y |   left_forefinger4_z |   left_middle_finger1_x |   left_middle_finger1_y |   left_middle_finger1_z |   left_middle_finger2_x |   left_middle_finger2_y |   left_middle_finger2_z |   left_middle_finger3_x |   left_middle_finger3_y |   left_middle_finger3_z |   left_middle_finger4_x |   left_middle_finger4_y |   left_middle_finger4_z |   left_ring_finger1_x |   left_ring_finger1_y |   left_ring_finger1_z |   left_ring_finger2_x |   left_ring_finger2_y |   left_ring_finger2_z |   left_ring_finger3_x |   left_ring_finger3_y |   left_ring_finger3_z |   left_ring_finger4_x |   left_ring_finger4_y |   left_ring_finger4_z |   left_pinky_finger1_x |   left_pinky_finger1_y |   left_pinky_finger1_z |   left_pinky_finger2_x |   left_pinky_finger2_y |   left_pinky_finger2_z |   left_pinky_finger3_x |   left_pinky_finger3_y |   left_pinky_finger3_z |   left_pinky_finger4_x |   left_pinky_finger4_y |   left_pinky_finger4_z |   right_hand_root_x |   right_hand_root_y |   right_hand_root_z |   right_thumb1_x |   right_thumb1_y |   right_thumb1_z |   right_thumb2_x |   right_thumb2_y |   right_thumb2_z |   right_thumb3_x |   right_thumb3_y |   right_thumb3_z |   right_thumb4_x |   right_thumb4_y |   right_thumb4_z |   right_forefinger1_x |   right_forefinger1_y |   right_forefinger1_z |   right_forefinger2_x |   right_forefinger2_y |   right_forefinger2_z |   right_forefinger3_x |   right_forefinger3_y |   right_forefinger3_z |   right_forefinger4_x |   right_forefinger4_y |   right_forefinger4_z |   right_middle_finger1_x |   right_middle_finger1_y |   right_middle_finger1_z |   right_middle_finger2_x |   right_middle_finger2_y |   right_middle_finger2_z |   right_middle_finger3_x |   right_middle_finger3_y |   right_middle_finger3_z |   right_middle_finger4_x |   right_middle_finger4_y |   right_middle_finger4_z |   right_ring_finger1_x |   right_ring_finger1_y |   right_ring_finger1_z |   right_ring_finger2_x |   right_ring_finger2_y |   right_ring_finger2_z |   right_ring_finger3_x |   right_ring_finger3_y |   right_ring_finger3_z |   right_ring_finger4_x |   right_ring_finger4_y |   right_ring_finger4_z |   right_pinky_finger1_x |   right_pinky_finger1_y |   right_pinky_finger1_z |   right_pinky_finger2_x |   right_pinky_finger2_y |   right_pinky_finger2_z |   right_pinky_finger3_x |   right_pinky_finger3_y |   right_pinky_finger3_z |   right_pinky_finger4_x |   right_pinky_finger4_y |   right_pinky_finger4_z |
|---:|------------:|---------:|---------:|---------:|-------------:|-------------:|-------------:|--------------:|--------------:|--------------:|-------------:|-------------:|-------------:|--------------:|--------------:|--------------:|------------------:|------------------:|------------------:|-------------------:|-------------------:|-------------------:|---------------:|---------------:|---------------:|----------------:|----------------:|----------------:|---------------:|---------------:|---------------:|----------------:|----------------:|----------------:|-------------:|-------------:|-------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|----------------:|----------------:|----------------:|-----------------:|-----------------:|-----------------:|-------------------:|-------------------:|-------------------:|--------------:|--------------:|--------------:|------------------:|------------------:|------------------:|--------------------:|--------------------:|--------------------:|---------------:|---------------:|---------------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|-------------------:|-------------------:|-------------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|--------------------:|--------------------:|--------------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|----------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-------------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|-----------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|

In [3]:
df_kaung = pd.read_csv('output/Kaung_skeleton_1.csv')
df_kaung.head()

,frame_idx,j0_x,j0_y,j0_z,j1_x,j1_y,j1_z,j2_x,j2_y,j2_z,...,j129_z,j130_x,j130_y,j130_z,j131_x,j131_y,j131_z,j132_x,j132_y,j132_z
0,0,-0.3743,-0.2373,8.7417,-0.3497,-0.2646,8.7692,-0.4033,-0.2616,8.7549,...,8.5985,-0.5595,0.2586,8.5915,-0.5600,0.2749,8.5944,-0.5606,0.2930,8.5977
1,1,-0.3771,-0.2317,8.7448,-0.3505,-0.2577,8.7633,-0.4036,-0.2556,8.7480,...,8.5901,-0.5571,0.2584,8.5872,-0.5574,0.2745,8.5852,-0.5583,0.2936,8.5934
2,2,-0.3744,-0.2239,8.7284,-0.3483,-0.2508,8.7523,-0.4046,-0.2497,8.7395,...,8.5974,-0.5555,0.2607,8.5904,-0.5557,0.2767,8.5883,-0.5584,0.2966,8.5962
3,3,-0.3746,-0.2126,8.7120,-0.3483,-0.2403,8.7305,-0.4025,-0.2390,8.7137,...,8.5875,-0.5547,0.2634,8.5902,-0.5529,0.2784,8.5837,-0.5559,0.2975,8.5963
4,4,-0.3737,-0.2031,8.7026,-0.3499,-0.2305,8.7264,-0.4029,-0.2274,8.7079,...,8.5944,-0.5535,0.2652,8.5877,-0.5541,0.2820,8.5909,-0.5527,0.3005,8.5898

In [4]:
print(df_kaung.head().to_markdown())

|    |   frame_idx |    j0_x |    j0_y |   j0_z |    j1_x |    j1_y |   j1_z |    j2_x |    j2_y |   j2_z |    j3_x |    j3_y |   j3_z |    j4_x |    j4_y |   j4_z |    j5_x |    j5_y |   j5_z |    j6_x |    j6_y |   j6_z |    j7_x |   j7_y |   j7_z |    j8_x |   j8_y |   j8_z |    j9_x |   j9_y |   j9_z |   j10_x |   j10_y |   j10_z |   j11_x |   j11_y |   j11_z |   j12_x |   j12_y |   j12_z |   j13_x |   j13_y |   j13_z |   j14_x |   j14_y |   j14_z |   j15_x |   j15_y |   j15_z |   j16_x |   j16_y |   j16_z |   j17_x |   j17_y |   j17_z |   j18_x |   j18_y |   j18_z |   j19_x |   j19_y |   j19_z |   j20_x |   j20_y |   j20_z |   j21_x |   j21_y |   j21_z |   j22_x |   j22_y |   j22_z |   j23_x |   j23_y |   j23_z |   j24_x |   j24_y |   j24_z |   j25_x |   j25_y |   j25_z |   j26_x |   j26_y |   j26_z |   j27_x |   j27_y |   j27_z |   j28_x |   j28_y |   j28_z |   j29_x |   j29_y |   j29_z |   j30_x |   j30_y |   j30_z |   j31_x |   j31_y |   j31_z |   j32_x |   j32_y |   j32_z |   j33_x |   j33_y |   j33_z |   j34_x |   j34_y |   j34_z |   j35_x |   j35_y |   j35_z |   j36_x |   j36_y |   j36_z |   j37_x |   j37_y |   j37_z |   j38_x |   j38_y |   j38_z |   j39_x |   j39_y |   j39_z |   j40_x |   j40_y |   j40_z |   j41_x |   j41_y |   j41_z |   j42_x |   j42_y |   j42_z |   j43_x |   j43_y |   j43_z |   j44_x |   j44_y |   j44_z |   j45_x |   j45_y |   j45_z |   j46_x |   j46_y |   j46_z |   j47_x |   j47_y |   j47_z |   j48_x |   j48_y |   j48_z |   j49_x |   j49_y |   j49_z |   j50_x |   j50_y |   j50_z |   j51_x |   j51_y |   j51_z |   j52_x |   j52_y |   j52_z |   j53_x |   j53_y |   j53_z |   j54_x |   j54_y |   j54_z |   j55_x |   j55_y |   j55_z |   j56_x |   j56_y |   j56_z |   j57_x |   j57_y |   j57_z |   j58_x |   j58_y |   j58_z |   j59_x |   j59_y |   j59_z |   j60_x |   j60_y |   j60_z |   j61_x |   j61_y |   j61_z |   j62_x |   j62_y |   j62_z |   j63_x |   j63_y |   j63_z |   j64_x |   j64_y |   j64_z |   j65_x |   j65_y |   j65_z |   j66_x |   j66_y |   j66_z |   j67_x |   j67_y |   j67_z |   j68_x |   j68_y |   j68_z |   j69_x |   j69_y |   j69_z |   j70_x |   j70_y |   j70_z |   j71_x |   j71_y |   j71_z |   j72_x |   j72_y |   j72_z |   j73_x |   j73_y |   j73_z |   j74_x |   j74_y |   j74_z |   j75_x |   j75_y |   j75_z |   j76_x |   j76_y |   j76_z |   j77_x |   j77_y |   j77_z |   j78_x |   j78_y |   j78_z |   j79_x |   j79_y |   j79_z |   j80_x |   j80_y |   j80_z |   j81_x |   j81_y |   j81_z |   j82_x |   j82_y |   j82_z |   j83_x |   j83_y |   j83_z |   j84_x |   j84_y |   j84_z |   j85_x |   j85_y |   j85_z |   j86_x |   j86_y |   j86_z |   j87_x |   j87_y |   j87_z |   j88_x |   j88_y |   j88_z |   j89_x |   j89_y |   j89_z |   j90_x |   j90_y |   j90_z |   j91_x |   j91_y |   j91_z |   j92_x |   j92_y |   j92_z |   j93_x |   j93_y |   j93_z |   j94_x |   j94_y |   j94_z |   j95_x |   j95_y |   j95_z |   j96_x |   j96_y |   j96_z |   j97_x |   j97_y |   j97_z |   j98_x |   j98_y |   j98_z |   j99_x |   j99_y |   j99_z |   j100_x |   j100_y |   j100_z |   j101_x |   j101_y |   j101_z |   j102_x |   j102_y |   j102_z |   j103_x |   j103_y |   j103_z |   j104_x |   j104_y |   j104_z |   j105_x |   j105_y |   j105_z |   j106_x |   j106_y |   j106_z |   j107_x |   j107_y |   j107_z |   j108_x |   j108_y |   j108_z |   j109_x |   j109_y |   j109_z |   j110_x |   j110_y |   j110_z |   j111_x |   j111_y |   j111_z |   j112_x |   j112_y |   j112_z |   j113_x |   j113_y |   j113_z |   j114_x |   j114_y |   j114_z |   j115_x |   j115_y |   j115_z |   j116_x |   j116_y |   j116_z |   j117_x |   j117_y |   j117_z |   j118_x |   j118_y |   j118_z |   j119_x |   j119_y |   j119_z |   j120_x |   j120_y |   j120_z |   j121_x |   j121_y |   j121_z |   j122_x |   j122_y |   j122_z |   j123_x |   j123_y |   j123_z |   j124_x |   j124_y |   j124_z |   j125_x |   j125_y |   j125_z |   j126_x |   j126_y |   j126_z |   j127_x |   j127_y |   j127_z |   j128_x |   j128_y |   j128_z |   j129_x |   j129_y |   j129_z |   j130_x |   j130_y |   j130_z |   j131_x |   j131_y |   j131_z |   j132_x |   j132_y |   j132_z |
|---:|------------:|--------:|--------:|-------:|--------:|--------:|-------:|--------:|--------:|-------:|--------:|--------:|-------:|--------:|--------:|-------:|--------:|--------:|-------:|--------:|--------:|-------:|--------:|-------:|-------:|--------:|-------:|-------:|--------:|-------:|-------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|
|  0 |           0 | -0.3743 | -0.2373 | 8.7417 | -0.3497 | -0.2646 | 8.7692 | -0.4033 | -0.2616 | 8.7549 | -0.3099 | -0.2432 | 8.8562 | -0.445  | -0.2434 | 8.7878 | -0.22   | -0.091  | 8.8967 | -0.5306 | -0.0858 | 8.7977 | -0.1677 | 0.1192 | 8.8957 | -0.6032 | 0.1158 | 8.7819 | -0.2155 | 0.2039 | 8.7723 | -0.5406 |  0.1852 |  8.6595 | -0.3105 |  0.2363 |  8.8613 | -0.449  |  0.2364 |  8.7518 | -0.2239 |  0.3047 |  8.7695 | -0.5276 |  0.3038 |  8.613  | -0.3326 |  0.6221 |  9.1088 | -0.4638 |  0.6103 |  8.7236 | -0.337  |  0.704  |  9.1466 | -0.2902 |  0.7029 |  9.1237 | -0.3741 |  0.6729 |  9.2151 | -0.4525 |  0.691  |  8.6159 | -0.5051 |  0.6835 |  8.651  | -0.439  |  0.6486 |  8.7661 | -0.4408 | -0.2622 |  8.7852 | -0.439  | -0.2457 |  8.7783 | -0.4356 | -0.2286 |  8.7772 | -0.4302 | -0.2131 |  8.7712 | -0.4253 | -0.198  |  8.7755 | -0.4166 | -0.1847 |  8.7755 | -0.4062 | -0.1742 |  8.7805 | -0.39   | -0.1681 |  8.7809 | -0.374  | -0.1676 |  8.7902 | -0.3558 | -0.1706 |  8.7893 | -0.3435 | -0.1783 |  8.8014 | -0.3308 | -0.1877 |  8.8081 | -0.322  | -0.2    |  8.8187 | -0.3184 | -0.2156 |  8.8272 | -0.3146 | -0.2303 |  8.8308 | -0.3126 | -0.2467 |  8.8337 | -0.3126 | -0.2642 |  8.841  | -0.425  | -0.2742 |  8.7618 | -0.4178 | -0.278  |  8.7632 | -0.4066 | -0.2787 |  8.756  | -0.3995 | -0.2789 |  8.7579 | -0.3906 | -0.2782 |  8.7607 | -0.3632 | -0.2781 |  8.7527 | -0.3564 | -0.2814 |  8.7644 | -0.3475 | -0.2816 |  8.7667 | -0.3368 | -0.28   |  8.7698 | -0.3301 | -0.277  |  8.7823 | -0.3758 | -0.2634 |  8.7467 | -0.3759 | -0.2525 |  8.7434 | -0.3759 | -0.2425 |  8.7401 | -0.3759 | -0.2334 |  8.7365 | -0.3871 | -0.2226 |  8.7405 | -0.3818 | -0.2219 |  8.7422 | -0.3745 | -0.2209 |  8.7391 | -0.3695 | -0.2223 |  8.7506 | -0.3624 | -0.2234 |  8.7524 | -0.416  | -0.2597 |  8.7566 | -0.4088 | -0.2626 |  8.7582 | -0.4017 | -0.2627 |  8.7602 | -0.3926 | -0.2619 |  8.7578 | -0.3998 | -0.259  |  8.7562 | -0.4089 | -0.259  |  8.7588 | -0.3602 | -0.2633 |  8.7613 | -0.3532 | -0.2654 |  8.768  | -0.3443 | -0.2647 |  8.7705 | -0.3374 | -0.2632 |  8.7777 | -0.3444 | -0.2611 |  8.7711 | -0.3533 | -0.2608 |  8.7686 | -0.4008 | -0.2041 |  8.7556 | -0.3916 | -0.2069 |  8.7526 | -0.3804 | -0.2085 |  8.7451 | -0.3748 | -0.2075 |  8.7415 | -0.3695 | -0.2086 |  8.7429 | -0.361  | -0.2073 |  8.7556 | -0.3504 | -0.2049 |  8.7589 | -0.3594 | -0.1993 |  8.7575 | -0.3664 | -0.1972 |  8.7509 | -0.3751 | -0.1959 |  8.7435 | -0.3825 | -0.196  |  8.7467 | -0.3916 | -0.1995 |  8.7488 | -0.3991 | -0.2033 |  8.7564 | -0.3841 | -0.2031 |  8.745  | -0.375  | -0.2031 |  8.7423 | -0.3665 | -0.2036 |  8.7548 | -0.3541 | -0.205  |  8.7631 | -0.3667 | -0.2038 |  8.7599 | -0.375  | -0.2031 |  8.7423 | -0.3841 | -0.2031 |  8.745  | -0.2187 |  0.2128 |  8.7482 | -0.2439 |  0.2238 |  8.7306 | -0.2693 |  0.2396 |  8.7183 | -0.2764 |  0.2584 |  8.7052 | -0.2797 |  0.2816 |  8.6834 | -0.2398 |  0.2472 |  8.6967 | -0.2418 |  0.2733 |  8.6903 | -0.2418 |  0.2947 |  8.6789 | -0.238  |  0.317  |  8.6629 |  -0.2165 |   0.253  |   8.7021 |  -0.2167 |   0.2799 |   8.6964 |  -0.2186 |   0.3023 |   8.6899 |  -0.2226 |   0.3251 |   8.6925 |  -0.2005 |   0.2582 |   8.7157 |  -0.1951 |   0.2822 |   8.7057 |  -0.1973 |   0.3022 |   8.7084 |  -0.2012 |   0.324  |   8.7111 |  -0.1861 |   0.2609 |   8.723  |  -0.1828 |   0.2797 |   8.727  |  -0.1811 |   0.2949 |   8.7248 |  -0.1813 |   0.3111 |   8.7223 |  -0.534  |   0.1931 |   8.6372 |  -0.5072 |   0.2032 |   8.6369 |  -0.4823 |   0.2189 |   8.6366 |  -0.4715 |   0.24   |   8.6286 |  -0.466  |   0.2603 |   8.6192 |  -0.5019 |   0.2266 |   8.5981 |  -0.4945 |   0.2523 |   8.5846 |  -0.4916 |   0.2729 |   8.5894 |  -0.4963 |   0.2958 |   8.6021 |  -0.5228 |   0.2316 |   8.5874 |  -0.5175 |   0.2583 |   8.5788 |  -0.5103 |   0.2812 |   8.5704 |  -0.5075 |   0.3027 |   8.5751 |  -0.5409 |   0.2365 |   8.5882 |  -0.541  |   0.2598 |   8.5821 |  -0.5397 |   0.2812 |   8.5818 |  -0.5365 |   0.3019 |   8.5814 |  -0.5577 |   0.2389 |   8.5985 |  -0.5595 |   0.2586 |   8.5915 |  -0.56   |   0.2749 |   8.5944 |  -0.5606 |   0.293  |   8.5977 |
|  1 |           1 | -0.3771 | -0.2317 | 8.7448 | -0.3505 | -0.2577 | 8.7633 | -0.4036 | -0.2556 | 8.748  | -0.3066 | -0.2374 | 8.8308 | -0.4445 | -0.2388 | 8.7697 | -0.2176 | -0.0917 | 8.8819 | -0.5284 | -0.0849 | 8.7937 | -0.1659 | 0.1214 | 8.8921 | -0.6061 | 0.1197 | 8.7762 | -0.2151 | 0.2039 | 8.7628 | -0.5388 |  0.1871 |  8.6608 | -0.31   |  0.2383 |  8.8656 | -0.4495 |  0.2393 |  8.7539 | -0.2241 |  0.3065 |  8.7855 | -0.5279 |  0.3035 |  8.6189 | -0.3349 |  0.6246 |  9.1402 | -0.4619 |  0.6107 |  8.7156 | -0.3364 |  0.7048 |  9.1514 | -0.2898 |  0.7029 |  9.1288 | -0.3734 |  0.6738 |  9.2194 | -0.4514 |  0.691  |  8.623  | -0.5053 |  0.6832 |  8.652  | -0.4393 |  0.6473 |  8.7628 | -0.4407 | -0.2561 |  8.7729 | -0.4388 | -0.2395 |  8.7657 | -0.4355 | -0.2234 |  8.7647 | -0.4302 | -0.208  |  8.7588 | -0.4253 | -0.192  |  8.7632 | -0.4188 | -0.1788 |  8.7728 | -0.4063 | -0.1673 |  8.7685 | -0.3924 | -0.1615 |  8.7788 | -0.3764 | -0.1609 |  8.7832 | -0.3582 | -0.1647 |  8.7824 | -0.344  | -0.1705 |  8.7904 | -0.3335 | -0.1809 |  8.8019 | -0.3246 | -0.194  |  8.8123 | -0.3171 | -0.2085 |  8.8118 | -0.3153 | -0.2241 |  8.8198 | -0.3114 | -0.2403 |  8.8181 | -0.3112 | -0.2566 |  8.8206 | -0.4249 | -0.2679 |  8.7495 | -0.4178 | -0.2726 |  8.7509 | -0.4086 | -0.2743 |  8.7482 | -0.3998 | -0.2737 |  8.751  | -0.391  | -0.2729 |  8.7537 | -0.3657 | -0.274  |  8.7506 | -0.3571 | -0.2753 |  8.7581 | -0.3484 | -0.2757 |  8.7657 | -0.3376 | -0.2739 |  8.7638 | -0.3309 | -0.2709 |  8.7765 | -0.3784 | -0.2557 |  8.745  | -0.3764 | -0.2465 |  8.7369 | -0.3784 | -0.2367 |  8.7381 | -0.3787 | -0.2269 |  8.7399 | -0.3896 | -0.2168 |  8.7384 | -0.3845 | -0.2153 |  8.7453 | -0.3773 | -0.2145 |  8.7425 | -0.3701 | -0.2164 |  8.7442 | -0.3652 | -0.2168 |  8.7558 | -0.416  | -0.2534 |  8.7444 | -0.4089 | -0.2563 |  8.7461 | -0.402  | -0.2566 |  8.7533 | -0.393  | -0.2558 |  8.7511 | -0.4001 | -0.2529 |  8.7493 | -0.409  | -0.2527 |  8.7467 | -0.3609 | -0.2563 |  8.7551 | -0.354  | -0.2575 |  8.7621 | -0.3451 | -0.2577 |  8.7645 | -0.338  | -0.2561 |  8.7667 | -0.3452 | -0.2541 |  8.7651 | -0.3541 | -0.254  |  8.7627 | -0.4012 | -0.1973 |  8.7488 | -0.392  | -0.2    |  8.746  | -0.3829 | -0.2019 |  8.7431 | -0.3776 | -0.202  |  8.7446 | -0.374  | -0.202  |  8.7456 | -0.3636 | -0.2016 |  8.7539 | -0.3552 | -0.1985 |  8.767  | -0.3642 | -0.1947 |  8.7652 | -0.3712 | -0.1908 |  8.7588 | -0.3779 | -0.1904 |  8.7467 | -0.387  | -0.1904 |  8.7492 | -0.392  | -0.1927 |  8.7421 | -0.3994 | -0.1973 |  8.7493 | -0.3866 | -0.1974 |  8.743  | -0.3777 | -0.1975 |  8.7455 | -0.3693 | -0.198  |  8.7581 | -0.3568 | -0.1983 |  8.7615 | -0.3693 | -0.1971 |  8.7581 | -0.3777 | -0.1966 |  8.7455 | -0.3866 | -0.1964 |  8.743  | -0.2203 |  0.2138 |  8.7482 | -0.2454 |  0.2239 |  8.7303 | -0.2687 |  0.2404 |  8.7131 | -0.2776 |  0.2601 |  8.6997 | -0.2806 |  0.2822 |  8.6727 | -0.2413 |  0.2482 |  8.6964 | -0.2431 |  0.2741 |  8.6851 | -0.2431 |  0.2955 |  8.6737 | -0.2392 |  0.3166 |  8.6529 |  -0.2179 |   0.253  |   8.697  |  -0.2163 |   0.2806 |   8.687  |  -0.2201 |   0.3031 |   8.6847 |  -0.2238 |   0.3264 |   8.6777 |  -0.2003 |   0.2591 |   8.7114 |  -0.1968 |   0.2838 |   8.7015 |  -0.1969 |   0.3045 |   8.6946 |  -0.2007 |   0.3243 |   8.6921 |  -0.186  |   0.2626 |   8.7192 |  -0.1807 |   0.2828 |   8.7091 |  -0.1809 |   0.297  |   8.7067 |  -0.1809 |   0.313  |   8.6993 |  -0.5322 |   0.194  |   8.6385 |  -0.5073 |   0.2041 |   8.6381 |  -0.4808 |   0.2189 |   8.6384 |  -0.47   |   0.24   |   8.6305 |  -0.4626 |   0.261  |   8.6166 |  -0.5002 |   0.2267 |   8.5992 |  -0.4929 |   0.2542 |   8.5862 |  -0.49   |   0.2747 |   8.5909 |  -0.493  |   0.2975 |   8.6041 |  -0.519  |   0.2323 |   8.5845 |  -0.5137 |   0.259  |   8.5756 |  -0.5086 |   0.2819 |   8.5717 |  -0.5038 |   0.3051 |   8.5724 |  -0.537  |   0.2372 |   8.5847 |  -0.5367 |   0.2604 |   8.5737 |  -0.5352 |   0.2825 |   8.5687 |  -0.5341 |   0.3042 |   8.5728 |  -0.5534 |   0.2404 |   8.5901 |  -0.5571 |   0.2584 |   8.5872 |  -0.5574 |   0.2745 |   8.5852 |  -0.5583 |   0.2936 |   8.5934 |

In [5]:
import re
from src.keypoints import keypoint_names

def to_friend_format(name):
    """Converts a name from your list to your friend's exact column naming convention."""
    name = name.lower()

    # 1. Expand L/R prefixes
    name = name.replace("l_", "left_").replace("r_", "right_")

    # 2. Fix Face and Hand Root
    name = name.replace("face_", "face-")
    name = name.replace("wrist_hand", "hand_root")

    # 3. Fix Feet (CamelCase to snake_case)
    name = name.replace("bigtoe", "big_toe").replace("smalltoe", "small_toe")

    # 4. Fix Fingers (Match friend's exact terminology)
    name = name.replace("index_", "forefinger_")
    name = name.replace("middle_", "middle_finger_")
    name = name.replace("ring_", "ring_finger_")
    name = name.replace("pinky_", "pinky_finger_")

    # 5. Remove the underscore before finger numbers (e.g., left_thumb_1 -> left_thumb1)
    if "finger" in name or "thumb" in name:
        name = re.sub(r"_(\d+)$", r"\1", name)

    return name

In [6]:
kaung_to_alisa = dict()
alisa_to_kaung = dict()

alisa_name = list()

for index, orig_name in enumerate(keypoint_names):
    friend_name = to_friend_format(orig_name)

    alisa_name.append(friend_name)

    for axis in ["x", "y", "z"]:
        my_col = f"j{index}_{axis}"
        friend_col = f"{friend_name}_{axis}"

        # Kaung's to Alisa's
        kaung_to_alisa[my_col] = friend_col
        # Alisa's to Kaung (Vice Versa)
        alisa_to_kaung[friend_col] = my_col

# print(json.dumps(kaung_to_alisa, indent=4))

In [7]:
# df_kaung.rename(columns=kaung_to_alisa, inplace=True)

In [8]:
df_alisa.rename(columns=alisa_to_kaung, inplace=True)

In [9]:
df_alisa.to_csv('output/4.csv')